[package]
version = "0.5.0"
name = "doitlater"
edition = "2018"
repository = "https://github.com/tyrylu/doitlater"
description = "A simple Redis based background jobs queue."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cron-parser = "0.11.2"
chrono = {version="0.4.43", default-features=false, features=["clock"]}
log = "0.4.29"
redis = "1.0.4"
serde = "1.0.228"
thiserror = "2.0.18"
typetag = "0.2.21"
bitcode = { version = "0.6.9", features = ["serde"] }

[[example]]
name = "basics"
