[package]
version = "0.2.2"
name = "doitlater"
edition = "2018"
repository = "https://github.com/tyrylu/doitlater"
description = "A simple Redis based background jobs queue."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4.22"
log = "0.4.17"
redis = "0.22.1"
saffron = "0.1.0"
serde = "1.0.147"
thiserror = "1.0.37"
typetag = "0.2.3"

[[example]]
name = "basics"
