[package]
name = "doitlater"
version = "0.1.2"
edition = "2018"
repository = "https://github.com/tyrylu/doitlater"
description = "A simple Redis based background jobs queue."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4.19"
log = "0.4.17"
redis = "0.21.5"
saffron = "0.1.0"
serde = "1.0.139"
thiserror = "1.0.31"
typetag = "0.2.1"

[[example]]
name = "basics"
