[package]
name = "doitlater"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4.19"
log = "0.4.14"
redis = "0.20.2"
saffron = "0.1.0"
serde = "1.0.126"
thiserror = "1.0.25"
typetag = "0.1.7"

[[example]]
name = "basics"